# This is a basic workflow to help you get started with Actions

name: Deploy Navi-Gateway to Container Registry

# Controls when the workflow will run
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Release to KDR CR
      - name: Deploy to Container Registry
        run: |
            rm -f NaviGateway/appsettings.json NaviGateway/appsettings.Development.json
            cp -vr NaviGateway/appsettings.Container.json NaviGateway/appsettings.json
            docker login ${{secrets.CONTAINER_REGISTRY}} --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_USERPASSWORD}}
            docker build -t navi_gateway:latest -f NaviGateway/Dockerfile .
            docker tag navi_gateway:latest ${{secrets.CONTAINER_REGISTRY}}/navi_gateway:latest
            docker push ${{secrets.CONTAINER_REGISTRY}}/navi_gateway:latest
